

%% The toggle switch example
% This toggle switch example was generated will a Hill kinetics model
% trained to a subset of the data provided in Lugagne et al. 2017. The
% example is baised in pseudo experimental-data which means that all data
% is generated by the model we have previously trained. This is a standard
% procedure that serves as means of benchmarking the algorithm.
%

clear variables;
clc;
close all;
noise_pseudo_data=0.05;

%%
% A number of settings is defined in the default configuration file. The
% assertiveness of these settings is problem dependent. Settings such as
% the number optimzation solver settings, the experiments considered, or
% number of models (sparsity cases) have default values that should be
% tailored to the problem. 

SBL_config_defaults;

%%
% As example we modify sbl_config.exp_idx for considering only experiments 1
% and 2.

sbl_config.exp_idx=1:3;
 
%% Generate and fit a family of models

%%
% We generate a family of models with SBL and fit with AMIGO+scatter search
% The convergence curves are given scatter search. Time courses for each
% modeled observable are also ploted along with the pseudo experimental
% data. There is substantial progess made by the parameter estimation
% process. 

MODELS=SBL_gen_model_family(sbl_config);
SBL_plotFamilyFit(MODELS);
set(gcf, 'Units', 'Normalized', 'OuterPosition', [0, 0.04, 1, 0.96]);

%% Execute OED for model discrimination

%% 
% Optimal experimental design for model discrimination seeks to find the
% experiment that maximizes the predicted different between the models.

modelsAfterOED=OED4SBLdiscrimination(MODELS,sbl_config);
SBL_plotDiscriminationResult(modelsAfterOED);
set(gcf, 'Units', 'Normalized', 'OuterPosition', [0, 0.04, 1, 0.96]);

%% Generate new pseudo experimental data
SBL_workdir;
data_file2_original=fullfile(SBL_work_dir,'Data',['experimental_data_loop_' num2str(1) '.csv']);
data_file2_pseudo=fullfile(SBL_work_dir,'Data','experimental_data_2_pseudo.csv');
add_pseudo_data(modelsAfterOED,noise_pseudo_data,data_file2_original,data_file2_pseudo,'model1');

%% Second iteration: generate and fit a family of models
sbl_config.exp_idx=[1 2 3 8];
% %% Generate and fit a new family of models
sbl_config.data_dir_name = fullfile(SBL_work_dir,'Data');
sbl_config.data_file_name = 'experimental_data_2_pseudo.csv';
MODELS=SBL_gen_model_family(sbl_config);
SBL_plotFamilyFit(MODELS);
set(gcf, 'Units', 'Normalized', 'OuterPosition', [0, 0.04, 1, 0.96]);

%% Second interation of OED for model discrimination

%% 
% Optimal experimental design for model discrimination seeks to find the
% experiment that maximizes the predicted different between the models.

modelsAfterOED=OED4SBLdiscrimination(MODELS,sbl_config);
SBL_plotDiscriminationResult(modelsAfterOED);
set(gcf, 'Units', 'Normalized', 'OuterPosition', [0, 0.04, 1, 0.96]);

%% Generate new pseudo experimental data
SBL_workdir;
data_file2_original=fullfile(SBL_work_dir,'Data','experimental_data_2_pseudo.csv');
data_file2_pseudo=fullfile(SBL_work_dir,'Data','experimental_data_3_pseudo.csv');
add_pseudo_data(modelsAfterOED,noise_pseudo_data,data_file2_original,data_file2_pseudo,'model1');


%% Third iteration: generate and fit a family of models
sbl_config.exp_idx=[1 2 3 8 9];
% %% Generate and fit a new family of models
sbl_config.data_dir_name = fullfile(SBL_work_dir,'Data');
sbl_config.data_file_name = 'experimental_data_3_pseudo.csv';
MODELS=SBL_gen_model_family(sbl_config);
SBL_plotFamilyFit(MODELS);
set(gcf, 'Units', 'Normalized', 'OuterPosition', [0, 0.04, 1, 0.96]);


%% Structural identifiability of the final familly of models

%% 
% 

res=SBL_structural_identifiability(sbl_config);








