
function [resGS] = GSens4SBL(inputs,model_name)

%% Model execution Global and local rank dont work yet in costMex mode
inputs.model.exe_type='standard';
inputs.model.odes_file=['Models/AutoGeneratedC/' model_name '.c'];
inputs.model.mexfile=['Models/AutoGeneratedC/' model_name 'standardMex'];
inputs.model.exe_type='standard';


%% SIMULATION
ivpsol={};
ivpsol.ivpsolver='cvodes';
ivpsol.senssolver='cvodes';
ivpsol.rtol=1.0D-6;
ivpsol.atol=1.0D-6;
inputs.ivpsol=ivpsol;

%% COST FUNCTION RELATED DATA
inputs.PEsol.PEcost_type='lsq';
inputs.PEsol.lsq_type='Q_expmax';

%% SIZE OF Latin Hypercube
inputs.rank.gr_samples=100;

%% Dont plot
inputs.plotd.plotlevel='noplot';

%% Run Global Rank of parameters
[inputs,privstruct] = AMIGO_Prep(inputs);
resGS = AMIGO_GRank(inputs);

end










































