
function [resPI] = RIdent4SBL(inputs,model_name)


%% Model execution Global and local rank dont work yet in costMex mode
inputs.model.exe_type='standard';
inputs.model.odes_file=['Models/AutoGeneratedC/' model_name '.c'];
inputs.model.mexfile=['Models/AutoGeneratedC/' model_name 'standardMex'];
inputs.model.exe_type='standard';

%% SIMULATION
ivpsol={};
ivpsol.ivpsolver='cvodes';
ivpsol.senssolver='cvodes';
ivpsol.rtol=1.0D-6;
ivpsol.atol=1.0D-6;
inputs.ivpsol=ivpsol;

%% COST FUNCTION RELATED DATA
inputs.PEsol.PEcost_type='llk';
inputs.PEsol.lsq_type='hetero';

%% OPTIMIZATION
inputs.nlpsol.nlpsolver='eSS';
inputs.nlpsol.eSS.maxeval = 100;
inputs.nlpsol.eSS.ndiverse = 30;
inputs.nlpsol.eSS.dim_refset = 6;
inputs.nlpsol.eSS.local.n1=0;
inputs.nlpsol.eSS.local.n2=0;
inputs.nlpsol.eSS.local.solver = 'fmincon'; 
inputs.nlpsol.eSS.local.finish =0;
inputs.nlpsol.eSS.maxtime=100;
inputs.plotd.plotlevel='noplot';

inputs.rid.conf_ntrials=100;

[inputs,privstruct] = AMIGO_Prep(inputs);
inputsPI=inputs;

resPI = AMIGO_RIdent(inputs);

end
